files:
  include: 'src/style/**/*.scss'
rules:
  indentation:
    - 2
    -
      size: 4
  property-sort-order:
    - 1
    -
      order: smacss
  nesting-depth:
    - 1
    -
      max-depth: 3
  no-css-comments: 0
  placeholder-in-extend: 0
  force-pseudo-nesting: 0
  force-attribute-nesting: 0
  no-qualifying-elements:
    - 1
    -
      allow-element-with-attribute: true
